//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSFactory.Quartz_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Quartz_Service.IJobService")]
    public interface IJobService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/AddScheduleJob", ReplyAction="http://tempuri.org/IJobService/AddScheduleJobResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.J_JobInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.J_JobTemplate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.J_JobTemplate))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.J_JobInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.RoleInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.RoleInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.ActionInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.ActionInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_UserInfo_ActionInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_UserInfo_ActionInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.UserInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.N_News[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.N_News))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_UserInfo_News[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_UserInfo_News))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_UserInfo_DepartmentInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_UserInfo_DepartmentInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.P_DepartmentInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.P_PersonInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.P_PersonInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.P_DepartmentInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.P_Group[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.P_Group))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_Group_Mission[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_Group_Mission))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.S_SMSMission))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_Department_Mission[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_Department_Mission))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_UserInfo_SMSMission[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_UserInfo_SMSMission))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.S_SMSContent[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.S_SMSContent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.S_SMSRecord_Current[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.S_SMSRecord_Current))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.S_SMSRecord_History[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.S_SMSRecord_History))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.S_SMSMsgContent[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.S_SMSMsgContent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_UserInfo_Group[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_UserInfo_Group))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_UserInfo_PersonInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_UserInfo_PersonInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.UserInfo[]))]
        bool AddScheduleJob(PMS.Model.J_JobInfo jobInfo, object jobData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/AddScheduleJob", ReplyAction="http://tempuri.org/IJobService/AddScheduleJobResponse")]
        System.Threading.Tasks.Task<bool> AddScheduleJobAsync(PMS.Model.J_JobInfo jobInfo, object jobData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/ResumeAllJob", ReplyAction="http://tempuri.org/IJobService/ResumeAllJobResponse")]
        void ResumeAllJob();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/ResumeAllJob", ReplyAction="http://tempuri.org/IJobService/ResumeAllJobResponse")]
        System.Threading.Tasks.Task ResumeAllJobAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/PauseJob", ReplyAction="http://tempuri.org/IJobService/PauseJobResponse")]
        void PauseJob(string jobName, string jobGroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/PauseJob", ReplyAction="http://tempuri.org/IJobService/PauseJobResponse")]
        System.Threading.Tasks.Task PauseJobAsync(string jobName, string jobGroup);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJobServiceChannel : SMSFactory.Quartz_Service.IJobService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JobServiceClient : System.ServiceModel.ClientBase<SMSFactory.Quartz_Service.IJobService>, SMSFactory.Quartz_Service.IJobService {
        
        public JobServiceClient() {
        }
        
        public JobServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JobServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddScheduleJob(PMS.Model.J_JobInfo jobInfo, object jobData) {
            return base.Channel.AddScheduleJob(jobInfo, jobData);
        }
        
        public System.Threading.Tasks.Task<bool> AddScheduleJobAsync(PMS.Model.J_JobInfo jobInfo, object jobData) {
            return base.Channel.AddScheduleJobAsync(jobInfo, jobData);
        }
        
        public void ResumeAllJob() {
            base.Channel.ResumeAllJob();
        }
        
        public System.Threading.Tasks.Task ResumeAllJobAsync() {
            return base.Channel.ResumeAllJobAsync();
        }
        
        public void PauseJob(string jobName, string jobGroup) {
            base.Channel.PauseJob(jobName, jobGroup);
        }
        
        public System.Threading.Tasks.Task PauseJobAsync(string jobName, string jobGroup) {
            return base.Channel.PauseJobAsync(jobName, jobGroup);
        }
    }
}
