//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionInfo
    {
        public int ID { get; set; }
        public int ParentID { get; set; }
        public string ActionInfoName { get; set; }
        public System.DateTime SubTime { get; set; }
        public bool DelFlag { get; set; }
        public System.DateTime ModifiedOnTime { get; set; }
        public string Remark { get; set; }
        public string Url { get; set; }
        public string AreaName { get; set; }
        public string ActionMethodName { get; set; }
        public string ControllerName { get; set; }
        public int Sort { get; set; }
        public short ActionTypeEnum { get; set; }
        public string MenuIcon { get; set; }
        public int IconWidth { get; set; }
        public int IconHeight { get; set; }
        public bool isShow { get; set; }
        public short MethodTypeEnum { get; set; }
    }
}
