//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FdfsTracker
    {
        public FdfsTracker()
        {
            this.FdfsContent = new HashSet<FdfsContent>();
        }
    
        public int TID { get; set; }
        public string URL { get; set; }
        public string Port { get; set; }
        public string GroupName { get; set; }
        public int StorePathIndex { get; set; }
    
        public virtual ICollection<FdfsContent> FdfsContent { get; set; }
    }
}
