//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FdfsContent
    {
        public FdfsContent()
        {
            this.S_SMSContent = new HashSet<S_SMSContent>();
        }
    
        public int ID { get; set; }
        public int TID { get; set; }
        public int SID { get; set; }
        public string FileName { get; set; }
        public string ScrollName { get; set; }
        public int Ext { get; set; }
    
        public virtual FdfsStorage FdfsStorage { get; set; }
        public virtual FdfsTracker FdfsTracker { get; set; }
        public virtual ICollection<S_SMSContent> S_SMSContent { get; set; }
    }
}
