//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class J_JobInfo
    {
        public J_JobInfo()
        {
            this.UserInfoes = new HashSet<UserInfo>();
            this.J_JobTemplate = new HashSet<J_JobTemplate>();
        }
    
        public int JID { get; set; }
        public string JobName { get; set; }
        public string JobGroup { get; set; }
        public string JobClassName { get; set; }
        public int JobState { get; set; }
        public string CronStr { get; set; }
        public System.DateTime StartRunTime { get; set; }
        public System.DateTime EndRunTime { get; set; }
        public System.DateTime NextRunTime { get; set; }
        public string Token { get; set; }
        public string AppID { get; set; }
        public string Remark { get; set; }
        public int InfoState { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool isDel { get; set; }
    
        public virtual ICollection<UserInfo> UserInfoes { get; set; }
        public virtual ICollection<J_JobTemplate> J_JobTemplate { get; set; }
    }
}
