//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class J_JobTemplate
    {
        public int JTID { get; set; }
        public string JobClassName { get; set; }
        public string CronStr { get; set; }
        public int JobType { get; set; }
        public string Remark { get; set; }
        public bool isDel { get; set; }
    }
}
