//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class J_JobTemplate
    {
        public J_JobTemplate()
        {
            this.UserInfoes = new HashSet<UserInfo>();
            this.J_JobInfo = new HashSet<J_JobInfo>();
            this.RoleInfo = new HashSet<RoleInfo>();
        }
    
        public int JTID { get; set; }
        public string JobClassName { get; set; }
        public string CronStr { get; set; }
        public int JobType { get; set; }
        public string Remark { get; set; }
        public bool isDel { get; set; }
        public string JTName { get; set; }
        public string JobGroup { get; set; }
        public bool isBtn { get; set; }
    
        public virtual ICollection<UserInfo> UserInfoes { get; set; }
        public virtual ICollection<J_JobInfo> J_JobInfo { get; set; }
        public virtual ICollection<RoleInfo> RoleInfo { get; set; }
    }
}
