//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Group1
    {
        public P_Group1()
        {
            this.R_Group_Mission = new HashSet<R_Group_Mission1>();
            this.R_UserInfo_Group = new HashSet<R_UserInfo_Group1>();
            this.P_PersonInfo = new HashSet<P_PersonInfo1>();
        }
    
        public int GID { get; set; }
        public string GroupName { get; set; }
        public System.DateTime SubTime { get; set; }
        public System.DateTime ModifiedOnTime { get; set; }
        public bool isDel { get; set; }
        public string Remark { get; set; }
        public int Sort { get; set; }
        public bool forbidDel { get; set; }
    
        public virtual ICollection<R_Group_Mission1> R_Group_Mission { get; set; }
        public virtual ICollection<R_UserInfo_Group1> R_UserInfo_Group { get; set; }
        public virtual ICollection<P_PersonInfo1> P_PersonInfo { get; set; }
    }
}
