//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_PersonInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public P_PersonInfo()
        {
            this.R_UserInfo_PersonInfo = new HashSet<R_UserInfo_PersonInfo>();
            this.S_SMSRecord_Current = new HashSet<S_SMSRecord_Current>();
            this.S_SMSRecord_History = new HashSet<S_SMSRecord_History>();
            this.P_DepartmentInfo = new HashSet<P_DepartmentInfo>();
            this.P_Group = new HashSet<P_Group>();
        }
    
        public int PID { get; set; }
        public string PName { get; set; }
        public string PhoneNum { get; set; }
        public string Remark { get; set; }
        public bool isVIP { get; set; }
        public bool isDel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_UserInfo_PersonInfo> R_UserInfo_PersonInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<S_SMSRecord_Current> S_SMSRecord_Current { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<S_SMSRecord_History> S_SMSRecord_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_DepartmentInfo> P_DepartmentInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_Group> P_Group { get; set; }
    }
}
