//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_PersonInfo1
    {
        public P_PersonInfo1()
        {
            this.R_UserInfo_PersonInfo = new HashSet<R_UserInfo_PersonInfo1>();
            this.S_SMSRecord_Current = new HashSet<S_SMSRecord_Current1>();
            this.S_SMSRecord_History = new HashSet<S_SMSRecord_History1>();
            this.P_DepartmentInfo = new HashSet<P_DepartmentInfo1>();
            this.P_Group = new HashSet<P_Group1>();
            this.P_PhoneNumber = new HashSet<P_PhoneNumber>();
            this.S_SMSType = new HashSet<S_SMSType>();
        }
    
        public int PID { get; set; }
        public string PName { get; set; }
        public string PhoneNum { get; set; }
        public string Remark { get; set; }
        public bool isVIP { get; set; }
        public bool isDel { get; set; }
    
        public virtual ICollection<R_UserInfo_PersonInfo1> R_UserInfo_PersonInfo { get; set; }
        public virtual ICollection<S_SMSRecord_Current1> S_SMSRecord_Current { get; set; }
        public virtual ICollection<S_SMSRecord_History1> S_SMSRecord_History { get; set; }
        public virtual ICollection<P_DepartmentInfo1> P_DepartmentInfo { get; set; }
        public virtual ICollection<P_Group1> P_Group { get; set; }
        public virtual ICollection<P_PhoneNumber> P_PhoneNumber { get; set; }
        public virtual ICollection<S_SMSType> S_SMSType { get; set; }
    }
}
