//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PMS2016Entities : DbContext
    {
        public PMS2016Entities()
            : base("name=PMS2016Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActionInfo> ActionInfo { get; set; }
        public virtual DbSet<P_DepartmentInfo> P_DepartmentInfo { get; set; }
        public virtual DbSet<P_Group> P_Group { get; set; }
        public virtual DbSet<P_PersonInfo> P_PersonInfo { get; set; }
        public virtual DbSet<R_Department_Mission> R_Department_Mission { get; set; }
        public virtual DbSet<R_Group_Mission> R_Group_Mission { get; set; }
        public virtual DbSet<R_UserInfo_ActionInfo> R_UserInfo_ActionInfo { get; set; }
        public virtual DbSet<R_UserInfo_DepartmentInfo> R_UserInfo_DepartmentInfo { get; set; }
        public virtual DbSet<R_UserInfo_Group> R_UserInfo_Group { get; set; }
        public virtual DbSet<R_UserInfo_PersonInfo> R_UserInfo_PersonInfo { get; set; }
        public virtual DbSet<R_UserInfo_SMSMission> R_UserInfo_SMSMission { get; set; }
        public virtual DbSet<RoleInfo> RoleInfo { get; set; }
        public virtual DbSet<S_SMSContent> S_SMSContent { get; set; }
        public virtual DbSet<S_SMSMission> S_SMSMission { get; set; }
        public virtual DbSet<S_SMSMsgContent> S_SMSMsgContent { get; set; }
        public virtual DbSet<S_SMSRecord_Current> S_SMSRecord_Current { get; set; }
        public virtual DbSet<S_SMSRecord_History> S_SMSRecord_History { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
    }
}
