//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quartz_Job
    {
        public int ID { get; set; }
        public string JobValue { get; set; }
        public string JobName { get; set; }
        public Nullable<int> State { get; set; }
        public string CronExpression { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public System.DateTime NextExecuteDate { get; set; }
        public string Token { get; set; }
        public string AppID { get; set; }
        public string ServiceCode { get; set; }
        public string InterfaceCode { get; set; }
        public string JobDecision { get; set; }
        public Nullable<int> DateState { get; set; }
        public System.DateTime CreateDateTime { get; set; }
    }
}
