//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_UserInfo_News
    {
        public R_UserInfo_News()
        {
            this.N_News = new HashSet<N_News>();
        }
    
        public int ID { get; set; }
        public int UID { get; set; }
        public int NID { get; set; }
        public bool isCheck { get; set; }
    
        public virtual ICollection<N_News> N_News { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
