//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_SMSRecord_History
    {
        public int SRID { get; set; }
        public int SCID { get; set; }
        public int PID { get; set; }
        public int StatusCode { get; set; }
        public string DescContent { get; set; }
    
        public virtual P_PersonInfo P_PersonInfo { get; set; }
        public virtual S_SMSContent S_SMSContent { get; set; }
    }
}
