//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_SMSMission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public S_SMSMission()
        {
            this.R_Department_Mission = new HashSet<R_Department_Mission>();
            this.R_Group_Mission = new HashSet<R_Group_Mission>();
            this.R_UserInfo_SMSMission = new HashSet<R_UserInfo_SMSMission>();
            this.S_SMSContent = new HashSet<S_SMSContent>();
            this.S_SMSMsgContent = new HashSet<S_SMSMsgContent>();
        }
    
        public int SMID { get; set; }
        public string SMSMissionName { get; set; }
        public System.DateTime SubTime { get; set; }
        public System.DateTime ModifiedOnTime { get; set; }
        public string Remark { get; set; }
        public bool isDel { get; set; }
        public bool isMMS { get; set; }
        public int Sort { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_Department_Mission> R_Department_Mission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_Group_Mission> R_Group_Mission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_UserInfo_SMSMission> R_UserInfo_SMSMission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<S_SMSContent> S_SMSContent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<S_SMSMsgContent> S_SMSMsgContent { get; set; }
    }
}
