//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_SMSMsgContent1
    {
        public int TID { get; set; }
        public int SMID { get; set; }
        public Nullable<int> UID { get; set; }
        public string MsgContent { get; set; }
        public bool isDel { get; set; }
        public System.DateTime SubTime { get; set; }
        public int Sort { get; set; }
        public string MsgName { get; set; }
        public string Remark { get; set; }
    
        public virtual S_SMSMission1 S_SMSMission { get; set; }
        public virtual UserInfo1 UserInfo { get; set; }
    }
}
