//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_SMSContent
    {
        public S_SMSContent()
        {
            this.S_SMSRecord_Current = new HashSet<S_SMSRecord_Current>();
            this.S_SMSRecord_History = new HashSet<S_SMSRecord_History>();
        }
    
        public int ID { get; set; }
        public int UID { get; set; }
        public string SMSContent { get; set; }
        public string msgId { get; set; }
        public System.DateTime SendDateTime { get; set; }
        public bool isDel { get; set; }
        public int SMID { get; set; }
        public string BlackList { get; set; }
        public int ResultCode { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<S_SMSRecord_Current> S_SMSRecord_Current { get; set; }
        public virtual S_SMSMission S_SMSMission { get; set; }
        public virtual ICollection<S_SMSRecord_History> S_SMSRecord_History { get; set; }
    }
}
