//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.R_UserInfo_ActionInfo = new HashSet<R_UserInfo_ActionInfo>();
            this.RoleInfo = new HashSet<RoleInfo>();
            this.R_UserInfo_Group = new HashSet<R_UserInfo_Group>();
            this.R_UserInfo_SMSMission = new HashSet<R_UserInfo_SMSMission>();
            this.S_SMSContent = new HashSet<S_SMSContent>();
            this.R_UserInfo_DepartmentInfo = new HashSet<R_UserInfo_DepartmentInfo>();
            this.R_UserInfo_PersonInfo = new HashSet<R_UserInfo_PersonInfo>();
            this.S_SMSMsgContent = new HashSet<S_SMSMsgContent>();
            this.R_UserInfo_News = new HashSet<R_UserInfo_News>();
            this.N_News = new HashSet<N_News>();
        }
    
        public int ID { get; set; }
        public string UName { get; set; }
        public string UPwd { get; set; }
        public bool DelFlag { get; set; }
        public System.DateTime SubTime { get; set; }
        public System.DateTime ModifiedOnTime { get; set; }
        public string Remark { get; set; }
        public int Sort { get; set; }
    
        public virtual ICollection<R_UserInfo_ActionInfo> R_UserInfo_ActionInfo { get; set; }
        public virtual ICollection<RoleInfo> RoleInfo { get; set; }
        public virtual ICollection<R_UserInfo_Group> R_UserInfo_Group { get; set; }
        public virtual ICollection<R_UserInfo_SMSMission> R_UserInfo_SMSMission { get; set; }
        public virtual ICollection<S_SMSContent> S_SMSContent { get; set; }
        public virtual ICollection<R_UserInfo_DepartmentInfo> R_UserInfo_DepartmentInfo { get; set; }
        public virtual ICollection<R_UserInfo_PersonInfo> R_UserInfo_PersonInfo { get; set; }
        public virtual ICollection<S_SMSMsgContent> S_SMSMsgContent { get; set; }
        public virtual ICollection<R_UserInfo_News> R_UserInfo_News { get; set; }
        public virtual ICollection<N_News> N_News { get; set; }
    }
}
