//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo1
    {
        public UserInfo1()
        {
            this.R_UserInfo_ActionInfo = new HashSet<R_UserInfo_ActionInfo1>();
            this.R_UserInfo_DepartmentInfo = new HashSet<R_UserInfo_DepartmentInfo1>();
            this.R_UserInfo_Group = new HashSet<R_UserInfo_Group1>();
            this.R_UserInfo_PersonInfo = new HashSet<R_UserInfo_PersonInfo1>();
            this.R_UserInfo_SMSMission = new HashSet<R_UserInfo_SMSMission1>();
            this.S_SMSContent = new HashSet<S_SMSContent1>();
            this.S_SMSMsgContent = new HashSet<S_SMSMsgContent1>();
            this.RoleInfoes = new HashSet<RoleInfo1>();
        }
    
        public int ID { get; set; }
        public string UName { get; set; }
        public string UPwd { get; set; }
        public bool DelFlag { get; set; }
        public System.DateTime SubTime { get; set; }
        public System.DateTime ModifiedOnTime { get; set; }
        public string Remark { get; set; }
        public int Sort { get; set; }
    
        public virtual ICollection<R_UserInfo_ActionInfo1> R_UserInfo_ActionInfo { get; set; }
        public virtual ICollection<R_UserInfo_DepartmentInfo1> R_UserInfo_DepartmentInfo { get; set; }
        public virtual ICollection<R_UserInfo_Group1> R_UserInfo_Group { get; set; }
        public virtual ICollection<R_UserInfo_PersonInfo1> R_UserInfo_PersonInfo { get; set; }
        public virtual ICollection<R_UserInfo_SMSMission1> R_UserInfo_SMSMission { get; set; }
        public virtual ICollection<S_SMSContent1> S_SMSContent { get; set; }
        public virtual ICollection<S_SMSMsgContent1> S_SMSMsgContent { get; set; }
        public virtual ICollection<RoleInfo1> RoleInfoes { get; set; }
    }
}
