//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_Query_StepInfo
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public bool isProcessed { get; set; }
        public bool isStartStep { get; set; }
        public bool isEndStep { get; set; }
        public string Title { get; set; }
        public string Comment { get; set; }
        public short StepResult { get; set; }
        public bool isDel { get; set; }
        public System.DateTime SubTime { get; set; }
        public System.DateTime ProcessTime { get; set; }
        public string Remark { get; set; }
        public int ProcessBy { get; set; }
        public int ParentStepId { get; set; }
        public int ChildStepId { get; set; }
        public int WF_Query { get; set; }
    }
}
