//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSFactory.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISMSService")]
    public interface ISMSService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSService/SendMsg", ReplyAction="http://tempuri.org/ISMSService/SendMsgResponse")]
        SMSFactory.ServiceReference1.SendMsgResponse SendMsg(SMSFactory.ServiceReference1.SendMsgRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSService/SendMsg", ReplyAction="http://tempuri.org/ISMSService/SendMsgResponse")]
        System.Threading.Tasks.Task<SMSFactory.ServiceReference1.SendMsgResponse> SendMsgAsync(SMSFactory.ServiceReference1.SendMsgRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMsg", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendMsgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public PMS.Model.SMSModel.SMSModel_Send smsdata;
        
        public SendMsgRequest() {
        }
        
        public SendMsgRequest(PMS.Model.SMSModel.SMSModel_Send smsdata) {
            this.smsdata = smsdata;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMsgResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendMsgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SendMsgResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public PMS.Model.SMSModel.SMSModel_Receive receiveModel;
        
        public SendMsgResponse() {
        }
        
        public SendMsgResponse(bool SendMsgResult, PMS.Model.SMSModel.SMSModel_Receive receiveModel) {
            this.SendMsgResult = SendMsgResult;
            this.receiveModel = receiveModel;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISMSServiceChannel : SMSFactory.ServiceReference1.ISMSService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSServiceClient : System.ServiceModel.ClientBase<SMSFactory.ServiceReference1.ISMSService>, SMSFactory.ServiceReference1.ISMSService {
        
        public SMSServiceClient() {
        }
        
        public SMSServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMSFactory.ServiceReference1.SendMsgResponse SMSFactory.ServiceReference1.ISMSService.SendMsg(SMSFactory.ServiceReference1.SendMsgRequest request) {
            return base.Channel.SendMsg(request);
        }
        
        public bool SendMsg(PMS.Model.SMSModel.SMSModel_Send smsdata, out PMS.Model.SMSModel.SMSModel_Receive receiveModel) {
            SMSFactory.ServiceReference1.SendMsgRequest inValue = new SMSFactory.ServiceReference1.SendMsgRequest();
            inValue.smsdata = smsdata;
            SMSFactory.ServiceReference1.SendMsgResponse retVal = ((SMSFactory.ServiceReference1.ISMSService)(this)).SendMsg(inValue);
            receiveModel = retVal.receiveModel;
            return retVal.SendMsgResult;
        }
        
        public System.Threading.Tasks.Task<SMSFactory.ServiceReference1.SendMsgResponse> SendMsgAsync(SMSFactory.ServiceReference1.SendMsgRequest request) {
            return base.Channel.SendMsgAsync(request);
        }
    }
}
