//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.BLL.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary2")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        PMS.BLL.ServiceReference1.CompositeType GetDataUsingDataContract(PMS.BLL.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<PMS.BLL.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(PMS.BLL.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddScheduleJob", ReplyAction="http://tempuri.org/IService1/AddScheduleJobResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.BLL.ServiceReference1.CompositeType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.J_JobInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.J_JobTemplate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.J_JobTemplate))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.J_JobInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.RoleInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.RoleInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.ActionInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.ActionInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_UserInfo_ActionInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_UserInfo_ActionInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.UserInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.N_News[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.N_News))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_UserInfo_News[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_UserInfo_News))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_UserInfo_DepartmentInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_UserInfo_DepartmentInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.P_DepartmentInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.P_PersonInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.P_PersonInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.P_DepartmentInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.P_Group[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.P_Group))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_Group_Mission[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_Group_Mission))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.S_SMSMission))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_Department_Mission[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_Department_Mission))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_UserInfo_SMSMission[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_UserInfo_SMSMission))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.S_SMSContent[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.S_SMSContent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.S_SMSRecord_Current[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.S_SMSRecord_Current))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.S_SMSRecord_History[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.S_SMSRecord_History))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.S_SMSMsgContent[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.S_SMSMsgContent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_UserInfo_Group[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_UserInfo_Group))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_UserInfo_PersonInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.R_UserInfo_PersonInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PMS.Model.UserInfo[]))]
        object AddScheduleJob(PMS.Model.J_JobInfo jobInfo, object data_temp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddScheduleJob", ReplyAction="http://tempuri.org/IService1/AddScheduleJobResponse")]
        System.Threading.Tasks.Task<object> AddScheduleJobAsync(PMS.Model.J_JobInfo jobInfo, object data_temp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PMS.BLL.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PMS.BLL.ServiceReference1.IService1>, PMS.BLL.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public PMS.BLL.ServiceReference1.CompositeType GetDataUsingDataContract(PMS.BLL.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<PMS.BLL.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(PMS.BLL.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public object AddScheduleJob(PMS.Model.J_JobInfo jobInfo, object data_temp) {
            return base.Channel.AddScheduleJob(jobInfo, data_temp);
        }
        
        public System.Threading.Tasks.Task<object> AddScheduleJobAsync(PMS.Model.J_JobInfo jobInfo, object data_temp) {
            return base.Channel.AddScheduleJobAsync(jobInfo, data_temp);
        }
    }
}
