//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 账号 的本地化字符串。
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 添加 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 添加联系人 的本地化字符串。
        /// </summary>
        internal static string AddContact {
            get {
                return ResourceManager.GetString("AddContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 高级搜索 的本地化字符串。
        /// </summary>
        internal static string AdvancedSearch {
            get {
                return ResourceManager.GetString("AdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 某天之后 的本地化字符串。
        /// </summary>
        internal static string After {
            get {
                return ResourceManager.GetString("After", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 全部消息 的本地化字符串。
        /// </summary>
        internal static string AllMessages {
            get {
                return ResourceManager.GetString("AllMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 全部用户 的本地化字符串。
        /// </summary>
        internal static string AllUsers {
            get {
                return ResourceManager.GetString("AllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 区域 的本地化字符串。
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 区域名称 的本地化字符串。
        /// </summary>
        internal static string AreaName {
            get {
                return ResourceManager.GetString("AreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 区域名 的本地化字符串。
        /// </summary>
        internal static string AreaName1 {
            get {
                return ResourceManager.GetString("AreaName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 确定要删除吗？ 的本地化字符串。
        /// </summary>
        internal static string Areyousureyouwanttodeleteit {
            get {
                return ResourceManager.GetString("Areyousureyouwanttodeleteit", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 分配作业模板 的本地化字符串。
        /// </summary>
        internal static string AssignTheRightofWorkTemplate {
            get {
                return ResourceManager.GetString("AssignTheRightofWorkTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 管理权限 的本地化字符串。
        /// </summary>
        internal static string Authority {
            get {
                return ResourceManager.GetString("Authority", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 权限管理 的本地化字符串。
        /// </summary>
        internal static string AuthorityManagement {
            get {
                return ResourceManager.GetString("AuthorityManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 某天之前 的本地化字符串。
        /// </summary>
        internal static string Before {
            get {
                return ResourceManager.GetString("Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 日历 的本地化字符串。
        /// </summary>
        internal static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 看不清，换一张 的本地化字符串。
        /// </summary>
        internal static string ChangeaPicture {
            get {
                return ResourceManager.GetString("ChangeaPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改部门 的本地化字符串。
        /// </summary>
        internal static string ChangeDepartment {
            get {
                return ResourceManager.GetString("ChangeDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改群组 的本地化字符串。
        /// </summary>
        internal static string ChangeGroup {
            get {
                return ResourceManager.GetString("ChangeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 当前用户发送短信趋势图 的本地化字符串。
        /// </summary>
        internal static string ChartofRecent10MessagesofCurrentUser {
            get {
                return ResourceManager.GetString("ChartofRecent10MessagesofCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户当日发送短信趋势图 的本地化字符串。
        /// </summary>
        internal static string ChartofTodaySendingRecordofCurrentUser {
            get {
                return ResourceManager.GetString("ChartofTodaySendingRecordofCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 选择 的本地化字符串。
        /// </summary>
        internal static string Choice {
            get {
                return ResourceManager.GetString("Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除/恢复的类型 的本地化字符串。
        /// </summary>
        internal static string ChoiceaType {
            get {
                return ResourceManager.GetString("ChoiceaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设置常用任务及群组 的本地化字符串。
        /// </summary>
        internal static string CommonMissionandGroupSetting {
            get {
                return ResourceManager.GetString("CommonMissionandGroupSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 联系人列表 的本地化字符串。
        /// </summary>
        internal static string ContactList {
            get {
                return ResourceManager.GetString("ContactList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 联系人列表 的本地化字符串。
        /// </summary>
        internal static string ContactList1 {
            get {
                return ResourceManager.GetString("ContactList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户名称 的本地化字符串。
        /// </summary>
        internal static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 联系人姓名 的本地化字符串。
        /// </summary>
        internal static string ContactName1 {
            get {
                return ResourceManager.GetString("ContactName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 指定联系人名称 的本地化字符串。
        /// </summary>
        internal static string ContactName2 {
            get {
                return ResourceManager.GetString("ContactName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 通讯录 的本地化字符串。
        /// </summary>
        internal static string ContactsList {
            get {
                return ResourceManager.GetString("ContactsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 通讯录更新公告 的本地化字符串。
        /// </summary>
        internal static string ContactsListUpdateNotice {
            get {
                return ResourceManager.GetString("ContactsListUpdateNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 内容 的本地化字符串。
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发送内容 的本地化字符串。
        /// </summary>
        internal static string Content1 {
            get {
                return ResourceManager.GetString("Content1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 消息内容 的本地化字符串。
        /// </summary>
        internal static string Content2 {
            get {
                return ResourceManager.GetString("Content2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 公告内容 的本地化字符串。
        /// </summary>
        internal static string Content3 {
            get {
                return ResourceManager.GetString("Content3", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 控制器名 的本地化字符串。
        /// </summary>
        internal static string ControllerName {
            get {
                return ResourceManager.GetString("ControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 控制器名称 的本地化字符串。
        /// </summary>
        internal static string ControllerName1 {
            get {
                return ResourceManager.GetString("ControllerName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 创建时间 的本地化字符串。
        /// </summary>
        internal static string CreateTime {
            get {
                return ResourceManager.GetString("CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新建权限 的本地化字符串。
        /// </summary>
        internal static string CreatingRights {
            get {
                return ResourceManager.GetString("CreatingRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新建角色 的本地化字符串。
        /// </summary>
        internal static string CreatingRoles {
            get {
                return ResourceManager.GetString("CreatingRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新建用户 的本地化字符串。
        /// </summary>
        internal static string CreatingUsers {
            get {
                return ResourceManager.GetString("CreatingUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Cron表达式 的本地化字符串。
        /// </summary>
        internal static string CronExpressions {
            get {
                return ResourceManager.GetString("CronExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 当前用户 的本地化字符串。
        /// </summary>
        internal static string CurrentUser {
            get {
                return ResourceManager.GetString("CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 当前用户 的本地化字符串。
        /// </summary>
        internal static string CurrentUser1 {
            get {
                return ResourceManager.GetString("CurrentUser1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查询日期 的本地化字符串。
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除公告 的本地化字符串。
        /// </summary>
        internal static string Delete1 {
            get {
                return ResourceManager.GetString("Delete1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除联系人 的本地化字符串。
        /// </summary>
        internal static string DeleteContact {
            get {
                return ResourceManager.GetString("DeleteContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除成功 的本地化字符串。
        /// </summary>
        internal static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 部门列表 的本地化字符串。
        /// </summary>
        internal static string DepartmentList {
            get {
                return ResourceManager.GetString("DepartmentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 部门管理 的本地化字符串。
        /// </summary>
        internal static string DepartmentManagement {
            get {
                return ResourceManager.GetString("DepartmentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 部门名称 的本地化字符串。
        /// </summary>
        internal static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 为当前短信任务分配部门 的本地化字符串。
        /// </summary>
        internal static string DepartmentSettingforSMSMission {
            get {
                return ResourceManager.GetString("DepartmentSettingforSMSMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 描述 的本地化字符串。
        /// </summary>
        internal static string Describe {
            get {
                return ResourceManager.GetString("Describe", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 我的桌面 的本地化字符串。
        /// </summary>
        internal static string DeskTop {
            get {
                return ResourceManager.GetString("DeskTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 禁用 的本地化字符串。
        /// </summary>
        internal static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否要执行此操作? 的本地化字符串。
        /// </summary>
        internal static string Doyouwanttodothis {
            get {
                return ResourceManager.GetString("Doyouwanttodothis", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 时间范围 的本地化字符串。
        /// </summary>
        internal static string During {
            get {
                return ResourceManager.GetString("During", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑 的本地化字符串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑联系人 的本地化字符串。
        /// </summary>
        internal static string EditContact {
            get {
                return ResourceManager.GetString("EditContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑公告 的本地化字符串。
        /// </summary>
        internal static string EdiTe {
            get {
                return ResourceManager.GetString("EdiTe", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑权限 的本地化字符串。
        /// </summary>
        internal static string EditingRights {
            get {
                return ResourceManager.GetString("EditingRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑用户 的本地化字符串。
        /// </summary>
        internal static string EditingUsers {
            get {
                return ResourceManager.GetString("EditingUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 启用 的本地化字符串。
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否禁用 的本地化字符串。
        /// </summary>
        internal static string EnableDisable {
            get {
                return ResourceManager.GetString("EnableDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 结束时间 的本地化字符串。
        /// </summary>
        internal static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 输入手机号码（不要输入固定电话） 的本地化字符串。
        /// </summary>
        internal static string Enterthephonenumber {
            get {
                return ResourceManager.GetString("Enterthephonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 输入相同密码 的本地化字符串。
        /// </summary>
        internal static string Enterthesamepassword {
            get {
                return ResourceManager.GetString("Enterthesamepassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 执行时间 的本地化字符串。
        /// </summary>
        internal static string ExecutionTime {
            get {
                return ResourceManager.GetString("ExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 操作失败 的本地化字符串。
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查询 的本地化字符串。
        /// </summary>
        internal static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 群组 的本地化字符串。
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 作业群组 的本地化字符串。
        /// </summary>
        internal static string Group1 {
            get {
                return ResourceManager.GetString("Group1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 群组列表 的本地化字符串。
        /// </summary>
        internal static string GroupList {
            get {
                return ResourceManager.GetString("GroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 群组管理 的本地化字符串。
        /// </summary>
        internal static string GroupManagement {
            get {
                return ResourceManager.GetString("GroupManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 群组名称 的本地化字符串。
        /// </summary>
        internal static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 群组名称 的本地化字符串。
        /// </summary>
        internal static string GroupName1 {
            get {
                return ResourceManager.GetString("GroupName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 为当前短信任务分配群组 的本地化字符串。
        /// </summary>
        internal static string GroupSettingforSMSMission {
            get {
                return ResourceManager.GetString("GroupSettingforSMSMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 输入短信内容 的本地化字符串。
        /// </summary>
        internal static string InputSMScontentplease {
            get {
                return ResourceManager.GetString("InputSMScontentplease", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 输入模板内容 的本地化字符串。
        /// </summary>
        internal static string Inputtemplatecontent {
            get {
                return ResourceManager.GetString("Inputtemplatecontent", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 作业类名 的本地化字符串。
        /// </summary>
        internal static string JobClassName {
            get {
                return ResourceManager.GetString("JobClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 最近一周 的本地化字符串。
        /// </summary>
        internal static string LastWeek {
            get {
                return ResourceManager.GetString("LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 数据加载中请稍候…… 的本地化字符串。
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 注销 的本地化字符串。
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 公告列表 的本地化字符串。
        /// </summary>
        internal static string MessageList {
            get {
                return ResourceManager.GetString("MessageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 消息通知 的本地化字符串。
        /// </summary>
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 消息及通知 的本地化字符串。
        /// </summary>
        internal static string MessagesManagement {
            get {
                return ResourceManager.GetString("MessagesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 公告类型 的本地化字符串。
        /// </summary>
        internal static string MessageType {
            get {
                return ResourceManager.GetString("MessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 方法名 的本地化字符串。
        /// </summary>
        internal static string MethodName {
            get {
                return ResourceManager.GetString("MethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 方法（权限）名称 的本地化字符串。
        /// </summary>
        internal static string MethodName1 {
            get {
                return ResourceManager.GetString("MethodName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 短信任务 的本地化字符串。
        /// </summary>
        internal static string Mission {
            get {
                return ResourceManager.GetString("Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查询任务种类 的本地化字符串。
        /// </summary>
        internal static string Mission1 {
            get {
                return ResourceManager.GetString("Mission1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 任务列表 的本地化字符串。
        /// </summary>
        internal static string MissionList {
            get {
                return ResourceManager.GetString("MissionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 任务管理 的本地化字符串。
        /// </summary>
        internal static string MissionManagement {
            get {
                return ResourceManager.GetString("MissionManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 任务名称 的本地化字符串。
        /// </summary>
        internal static string MissionName {
            get {
                return ResourceManager.GetString("MissionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 任务名称必须填写 的本地化字符串。
        /// </summary>
        internal static string Missionnamemustbefilled {
            get {
                return ResourceManager.GetString("Missionnamemustbefilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 最后修改时间 的本地化字符串。
        /// </summary>
        internal static string ModifiedTime {
            get {
                return ResourceManager.GetString("ModifiedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改密码 的本地化字符串。
        /// </summary>
        internal static string ModifyPassword {
            get {
                return ResourceManager.GetString("ModifyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改成功 的本地化字符串。
        /// </summary>
        internal static string ModifySuccess {
            get {
                return ResourceManager.GetString("ModifySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 移至分组 的本地化字符串。
        /// </summary>
        internal static string MoveIntoGroup {
            get {
                return ResourceManager.GetString("MoveIntoGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 姓名 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 匹配名称 的本地化字符串。
        /// </summary>
        internal static string NameMaching {
            get {
                return ResourceManager.GetString("NameMaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新增 的本地化字符串。
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新增公告 的本地化字符串。
        /// </summary>
        internal static string NewMessage {
            get {
                return ResourceManager.GetString("NewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新密码 的本地化字符串。
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新用户名 的本地化字符串。
        /// </summary>
        internal static string NewUserName {
            get {
                return ResourceManager.GetString("NewUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 下次执行 的本地化字符串。
        /// </summary>
        internal static string NextExecutionTime {
            get {
                return ResourceManager.GetString("NextExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 未收到人数 的本地化字符串。
        /// </summary>
        internal static string NotReceived {
            get {
                return ResourceManager.GetString("NotReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 匹配电话 的本地化字符串。
        /// </summary>
        internal static string NumberMatching {
            get {
                return ResourceManager.GetString("NumberMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 具体某天 的本地化字符串。
        /// </summary>
        internal static string OneDay {
            get {
                return ResourceManager.GetString("OneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 操作 的本地化字符串。
        /// </summary>
        internal static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 操作列表 的本地化字符串。
        /// </summary>
        internal static string OperationList {
            get {
                return ResourceManager.GetString("OperationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 可选 的本地化字符串。
        /// </summary>
        internal static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 可选，Cron表达式 的本地化字符串。
        /// </summary>
        internal static string OptionalCronexpression {
            get {
                return ResourceManager.GetString("OptionalCronexpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 顺序 的本地化字符串。
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 系统介绍公告 的本地化字符串。
        /// </summary>
        internal static string OtherNotice {
            get {
                return ResourceManager.GetString("OtherNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string Password1 {
            get {
                return ResourceManager.GetString("Password1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 电话号码 的本地化字符串。
        /// </summary>
        internal static string Phonenumber {
            get {
                return ResourceManager.GetString("Phonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 电话号码 的本地化字符串。
        /// </summary>
        internal static string PhoneNumber1 {
            get {
                return ResourceManager.GetString("PhoneNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 匹配电话号码 的本地化字符串。
        /// </summary>
        internal static string PhoneNumber2 {
            get {
                return ResourceManager.GetString("PhoneNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选择该部门属于哪个上级机构 的本地化字符串。
        /// </summary>
        internal static string Pleasechoosethesuperiorofthisdepartment {
            get {
                return ResourceManager.GetString("Pleasechoosethesuperiorofthisdepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请确认 的本地化字符串。
        /// </summary>
        internal static string Pleaseconfirm {
            get {
                return ResourceManager.GetString("Pleaseconfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请描述群组功能（可选） 的本地化字符串。
        /// </summary>
        internal static string Pleasedescribethegroupoptional {
            get {
                return ResourceManager.GetString("Pleasedescribethegroupoptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请输入新的登录密码 的本地化字符串。
        /// </summary>
        internal static string Pleaseenteranewloginpassword {
            get {
                return ResourceManager.GetString("Pleaseenteranewloginpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请输入备注 的本地化字符串。
        /// </summary>
        internal static string Pleaseenterasubject {
            get {
                return ResourceManager.GetString("Pleaseenterasubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请输入登录密码 的本地化字符串。
        /// </summary>
        internal static string Pleaseenterpassword {
            get {
                return ResourceManager.GetString("Pleaseenterpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请再次输入密码 的本地化字符串。
        /// </summary>
        internal static string Pleaseenterpasswordagain {
            get {
                return ResourceManager.GetString("Pleaseenterpasswordagain", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请填写作业对应的类名称 的本地化字符串。
        /// </summary>
        internal static string Pleaseentertheclassname {
            get {
                return ResourceManager.GetString("Pleaseentertheclassname", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请输入联系人姓名 的本地化字符串。
        /// </summary>
        internal static string Pleaseenterthecontactname {
            get {
                return ResourceManager.GetString("Pleaseenterthecontactname", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请输入该任务所属的模板内容 的本地化字符串。
        /// </summary>
        internal static string Pleaseenterthecontentofthistemplate {
            get {
                return ResourceManager.GetString("Pleaseenterthecontentofthistemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请填写控制器名称 的本地化字符串。
        /// </summary>
        internal static string Pleaseenterthecontrollername {
            get {
                return ResourceManager.GetString("Pleaseenterthecontrollername", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请填写CronStr 的本地化字符串。
        /// </summary>
        internal static string PleaseentertheCronStr {
            get {
                return ResourceManager.GetString("PleaseentertheCronStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请填写群组名称 的本地化字符串。
        /// </summary>
        internal static string Pleaseenterthegroupname {
            get {
                return ResourceManager.GetString("Pleaseenterthegroupname", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请填写作业所属于的群组 的本地化字符串。
        /// </summary>
        internal static string Pleaseenterthegroupofthiswork {
            get {
                return ResourceManager.GetString("Pleaseenterthegroupofthiswork", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请填写控制器中方法名称 的本地化字符串。
        /// </summary>
        internal static string Pleaseenterthemethodname {
            get {
                return ResourceManager.GetString("Pleaseenterthemethodname", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请填写权限名称 的本地化字符串。
        /// </summary>
        internal static string Pleaseenterthenameofright {
            get {
                return ResourceManager.GetString("Pleaseenterthenameofright", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请填写区域名称 的本地化字符串。
        /// </summary>
        internal static string Pleaseenterthenameofthearea {
            get {
                return ResourceManager.GetString("Pleaseenterthenameofthearea", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请输入该部门的名称（只能填写中文） 的本地化字符串。
        /// </summary>
        internal static string Pleaseenterthenameofthedepartment {
            get {
                return ResourceManager.GetString("Pleaseenterthenameofthedepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请填写任务名称（请输入中文） 的本地化字符串。
        /// </summary>
        internal static string Pleaseenterthenameofthemission {
            get {
                return ResourceManager.GetString("Pleaseenterthenameofthemission", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请填写角色名称 的本地化字符串。
        /// </summary>
        internal static string Pleaseentertherolename {
            get {
                return ResourceManager.GetString("Pleaseentertherolename", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请填写模板名称 的本地化字符串。
        /// </summary>
        internal static string PleaseenterthetemplateName {
            get {
                return ResourceManager.GetString("PleaseenterthetemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请输入模板类型（整数） 的本地化字符串。
        /// </summary>
        internal static string Pleaseenterthetemplatetypeinteger {
            get {
                return ResourceManager.GetString("Pleaseenterthetemplatetypeinteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请填写题目，长度不超过50字 的本地化字符串。
        /// </summary>
        internal static string Pleaseenterthetitlenomorethan50words {
            get {
                return ResourceManager.GetString("Pleaseenterthetitlenomorethan50words", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请填写模板类名 的本地化字符串。
        /// </summary>
        internal static string Pleaseentertheworktemplatesclassname {
            get {
                return ResourceManager.GetString("Pleaseentertheworktemplatesclassname", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请填写模板群组名 的本地化字符串。
        /// </summary>
        internal static string Pleaseentertheworktemplatesgroupname {
            get {
                return ResourceManager.GetString("Pleaseentertheworktemplatesgroupname", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请填写系统登录用户名 的本地化字符串。
        /// </summary>
        internal static string Pleaseenterusername {
            get {
                return ResourceManager.GetString("Pleaseenterusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请填写作业名称 的本地化字符串。
        /// </summary>
        internal static string Pleaseenterworkname {
            get {
                return ResourceManager.GetString("Pleaseenterworkname", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请从左侧输入登录账号和密码登录
        ///如果遇到系统问题，请联系网络管理员。
        ///如果没有账号，请联系网络管理员。 的本地化字符串。
        /// </summary>
        internal static string PleaseenteryouraccountandpasswordIfyouhaveanyproblemspleaseContacttheadministraTor {
            get {
                return ResourceManager.GetString("PleaseenteryouraccountandpasswordIfyouhaveanyproblemspleaseContacttheadministraTo" +
                        "r", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请填写模板名称 的本地化字符串。
        /// </summary>
        internal static string PleasefillinthetemplateName {
            get {
                return ResourceManager.GetString("PleasefillinthetemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选择 的本地化字符串。
        /// </summary>
        internal static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选中某一个人 的本地化字符串。
        /// </summary>
        internal static string Pleaseselectaperson {
            get {
                return ResourceManager.GetString("Pleaseselectaperson", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选择该模板所属的短信任务种类 的本地化字符串。
        /// </summary>
        internal static string Pleaseselectthesuitablemissionforthistemplate {
            get {
                return ResourceManager.GetString("Pleaseselectthesuitablemissionforthistemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选择你常用的短信群组
        ///（此群组会出现在发送界面的短信任务列表中）
        /// 的本地化字符串。
        /// </summary>
        internal static string PleaseselectyourcommongroupsSelectedgroupswillappearsinthelistofmessagesendinginterface {
            get {
                return ResourceManager.GetString("PleaseselectyourcommongroupsSelectedgroupswillappearsinthelistofmessagesendingint" +
                        "erface", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选择你常用的短信任务种类
        ///（此任务会出现在发送界面的短信任务列表中） 的本地化字符串。
        /// </summary>
        internal static string PleaseselectyourcommonmissionsSelectedmissionswillappearsinthelistofmessagesendinginterface {
            get {
                return ResourceManager.GetString("PleaseselectyourcommonmissionsSelectedmissionswillappearsinthelistofmessagesendin" +
                        "ginterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 优先级 的本地化字符串。
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string Prompt {
            get {
                return ResourceManager.GetString("Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查询作业 的本地化字符串。
        /// </summary>
        internal static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查询区域名 的本地化字符串。
        /// </summary>
        internal static string QueryAreaName {
            get {
                return ResourceManager.GetString("QueryAreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查询控制器 的本地化字符串。
        /// </summary>
        internal static string QueryControllerName {
            get {
                return ResourceManager.GetString("QueryControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查询方法名 的本地化字符串。
        /// </summary>
        internal static string QueryMethodName {
            get {
                return ResourceManager.GetString("QueryMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查询备注 的本地化字符串。
        /// </summary>
        internal static string QueryRemarks {
            get {
                return ResourceManager.GetString("QueryRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查询权限名 的本地化字符串。
        /// </summary>
        internal static string QueryRightName {
            get {
                return ResourceManager.GetString("QueryRightName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查询角色名 的本地化字符串。
        /// </summary>
        internal static string QueryRoleName {
            get {
                return ResourceManager.GetString("QueryRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查询用户名 的本地化字符串。
        /// </summary>
        internal static string QueryUserName {
            get {
                return ResourceManager.GetString("QueryUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 准备提交？ 的本地化字符串。
        /// </summary>
        internal static string Readytocommit {
            get {
                return ResourceManager.GetString("Readytocommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 收到 的本地化字符串。
        /// </summary>
        internal static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 接收状态 的本地化字符串。
        /// </summary>
        internal static string Receiving {
            get {
                return ResourceManager.GetString("Receiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 当前用户发送短信统计 的本地化字符串。
        /// </summary>
        internal static string Recent10MessagesofCurrentUser {
            get {
                return ResourceManager.GetString("Recent10MessagesofCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 该用户近十条短信 的本地化字符串。
        /// </summary>
        internal static string Recent10MessagesofCurrentUser1 {
            get {
                return ResourceManager.GetString("Recent10MessagesofCurrentUser1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 恢复 的本地化字符串。
        /// </summary>
        internal static string Recovery {
            get {
                return ResourceManager.GetString("Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 恢复 的本地化字符串。
        /// </summary>
        internal static string Recovery1 {
            get {
                return ResourceManager.GetString("Recovery1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 回收站 的本地化字符串。
        /// </summary>
        internal static string Recycle {
            get {
                return ResourceManager.GetString("Recycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发布时间 的本地化字符串。
        /// </summary>
        internal static string ReleaseTime {
            get {
                return ResourceManager.GetString("ReleaseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 记住我 的本地化字符串。
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请求类型 的本地化字符串。
        /// </summary>
        internal static string RequestType {
            get {
                return ResourceManager.GetString("RequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 重置密码 的本地化字符串。
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 权限名称 的本地化字符串。
        /// </summary>
        internal static string RightName {
            get {
                return ResourceManager.GetString("RightName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑角色 的本地化字符串。
        /// </summary>
        internal static string RoleEditing {
            get {
                return ResourceManager.GetString("RoleEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 角色管理 的本地化字符串。
        /// </summary>
        internal static string RoleManagement {
            get {
                return ResourceManager.GetString("RoleManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 角色名称 的本地化字符串。
        /// </summary>
        internal static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 为角色设置权限 的本地化字符串。
        /// </summary>
        internal static string RolesRightSettings {
            get {
                return ResourceManager.GetString("RolesRightSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 保存分配结果 的本地化字符串。
        /// </summary>
        internal static string Save1 {
            get {
                return ResourceManager.GetString("Save1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请先选择短信任务种类 的本地化字符串。
        /// </summary>
        internal static string Selectamission {
            get {
                return ResourceManager.GetString("Selectamission", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 选择日期 的本地化字符串。
        /// </summary>
        internal static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 选择所属部门 的本地化字符串。
        /// </summary>
        internal static string SelectDepartment {
            get {
                return ResourceManager.GetString("SelectDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请至少选中一行数据 的本地化字符串。
        /// </summary>
        internal static string Selectonelineofdataatleast {
            get {
                return ResourceManager.GetString("Selectonelineofdataatleast", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选择一行数据 的本地化字符串。
        /// </summary>
        internal static string Selectonelineofdataplease {
            get {
                return ResourceManager.GetString("Selectonelineofdataplease", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 选择该部门所在的区域 的本地化字符串。
        /// </summary>
        internal static string SelecttheareaoftheDepartment {
            get {
                return ResourceManager.GetString("SelecttheareaoftheDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 选择任职部门 的本地化字符串。
        /// </summary>
        internal static string Selectthedepartment {
            get {
                return ResourceManager.GetString("Selectthedepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选择公告类型 的本地化字符串。
        /// </summary>
        internal static string Selectthetypeofmessage {
            get {
                return ResourceManager.GetString("Selectthetypeofmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 选择该权限所属的上级菜单 的本地化字符串。
        /// </summary>
        internal static string Selecttheuppermenuforthispermission {
            get {
                return ResourceManager.GetString("Selecttheuppermenuforthispermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 选择该权限所属的上级菜单 的本地化字符串。
        /// </summary>
        internal static string Selecttheuppermenuforthispermission1 {
            get {
                return ResourceManager.GetString("Selecttheuppermenuforthispermission1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 共发送 的本地化字符串。
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发送作业 的本地化字符串。
        /// </summary>
        internal static string Send1 {
            get {
                return ResourceManager.GetString("Send1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 彩信发送 的本地化字符串。
        /// </summary>
        internal static string SendMMS {
            get {
                return ResourceManager.GetString("SendMMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发送总人数 的本地化字符串。
        /// </summary>
        internal static string SendNumber {
            get {
                return ResourceManager.GetString("SendNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发送短信条数 的本地化字符串。
        /// </summary>
        internal static string SendNumber1 {
            get {
                return ResourceManager.GetString("SendNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发送短信 的本地化字符串。
        /// </summary>
        internal static string SendSMS {
            get {
                return ResourceManager.GetString("SendSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户发送统计 的本地化字符串。
        /// </summary>
        internal static string SendStatistics {
            get {
                return ResourceManager.GetString("SendStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发送统计 的本地化字符串。
        /// </summary>
        internal static string SendStatistics1 {
            get {
                return ResourceManager.GetString("SendStatistics1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发送时间 的本地化字符串。
        /// </summary>
        internal static string SendTime {
            get {
                return ResourceManager.GetString("SendTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 服务器错误 的本地化字符串。
        /// </summary>
        internal static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设置常用短信群组 的本地化字符串。
        /// </summary>
        internal static string SetCommonGroup {
            get {
                return ResourceManager.GetString("SetCommonGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设置常用短信任务 的本地化字符串。
        /// </summary>
        internal static string SetCommonMission {
            get {
                return ResourceManager.GetString("SetCommonMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 个人设置 的本地化字符串。
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设置VIP联系人 的本地化字符串。
        /// </summary>
        internal static string SetVIPcontacts {
            get {
                return ResourceManager.GetString("SetVIPcontacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 显示xx到xx，共xx条记录 的本地化字符串。
        /// </summary>
        internal static string ShowXXtoXXinXXrecords {
            get {
                return ResourceManager.GetString("ShowXXtoXXinXXrecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 登录 的本地化字符串。
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 短信发送 的本地化字符串。
        /// </summary>
        internal static string SMS {
            get {
                return ResourceManager.GetString("SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 短信内容 的本地化字符串。
        /// </summary>
        internal static string SMSContent {
            get {
                return ResourceManager.GetString("SMSContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 短信编辑 的本地化字符串。
        /// </summary>
        internal static string SMSEditor {
            get {
                return ResourceManager.GetString("SMSEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 短信任务 的本地化字符串。
        /// </summary>
        internal static string SMSMission {
            get {
                return ResourceManager.GetString("SMSMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 国家海洋环境预报中心短信系统 的本地化字符串。
        /// </summary>
        internal static string SMSPlatformofNMEFC {
            get {
                return ResourceManager.GetString("SMSPlatformofNMEFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 国家海洋环境预报中心短信云平台 的本地化字符串。
        /// </summary>
        internal static string SMSPlatformofNMEFC1 {
            get {
                return ResourceManager.GetString("SMSPlatformofNMEFC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 短信任务名称 的本地化字符串。
        /// </summary>
        internal static string SMSTaskName {
            get {
                return ResourceManager.GetString("SMSTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 短信统计 的本地化字符串。
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 题目 的本地化字符串。
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 提交 的本地化字符串。
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 操作成功 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 所属任务 的本地化字符串。
        /// </summary>
        internal static string SuitableMission {
            get {
                return ResourceManager.GetString("SuitableMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 所属上级机构 的本地化字符串。
        /// </summary>
        internal static string SuperiorDepartment {
            get {
                return ResourceManager.GetString("SuperiorDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 暂停 的本地化字符串。
        /// </summary>
        internal static string Suspend {
            get {
                return ResourceManager.GetString("Suspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 系统维护公告 的本地化字符串。
        /// </summary>
        internal static string SystemMaintenanceNotice {
            get {
                return ResourceManager.GetString("SystemMaintenanceNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 系统管理 的本地化字符串。
        /// </summary>
        internal static string SystemManagement {
            get {
                return ResourceManager.GetString("SystemManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 短信模板 的本地化字符串。
        /// </summary>
        internal static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 模板类名 的本地化字符串。
        /// </summary>
        internal static string Templateclass {
            get {
                return ResourceManager.GetString("Templateclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 模板群组名称 的本地化字符串。
        /// </summary>
        internal static string TemplateGroupName {
            get {
                return ResourceManager.GetString("TemplateGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 模板名称 的本地化字符串。
        /// </summary>
        internal static string TemplateName {
            get {
                return ResourceManager.GetString("TemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 添加临时联系人 的本地化字符串。
        /// </summary>
        internal static string TemporaryContacts {
            get {
                return ResourceManager.GetString("TemporaryContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 终止 的本地化字符串。
        /// </summary>
        internal static string Termination {
            get {
                return ResourceManager.GetString("Termination", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 作业执行的时间 的本地化字符串。
        /// </summary>
        internal static string Themessagesendingtime {
            get {
                return ResourceManager.GetString("Themessagesendingtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 数字越小优先级越高 的本地化字符串。
        /// </summary>
        internal static string Thesmallerthenumberthehigherthepriority {
            get {
                return ResourceManager.GetString("Thesmallerthenumberthehigherthepriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否开启定时发送 的本地化字符串。
        /// </summary>
        internal static string Theswitchofdelayedsending {
            get {
                return ResourceManager.GetString("Theswitchofdelayedsending", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 作业执行的时间 的本地化字符串。
        /// </summary>
        internal static string Thetimeofworkexecution {
            get {
                return ResourceManager.GetString("Thetimeofworkexecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 本月 的本地化字符串。
        /// </summary>
        internal static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 该权限由角色赋予，不可取消勾选该权限。如不想分配该权限给该用户，请在“分配角色”按钮下操作，或点击‘禁用’。如有疑问，请联系管理员 的本地化字符串。
        /// </summary>
        internal static string ThisrightisgivenbyrolesandcannotbeuncheckedYoucantrytoclickDisableoreditingtheroleinassignrolesbutton {
            get {
                return ResourceManager.GetString("ThisrightisgivenbyrolesandcannotbeuncheckedYoucantrytoclickDisableoreditingtherol" +
                        "einassignrolesbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 开启定时发送 的本地化字符串。
        /// </summary>
        internal static string TimerOnOff {
            get {
                return ResourceManager.GetString("TimerOnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设置发送时间 的本地化字符串。
        /// </summary>
        internal static string TimerSetting {
            get {
                return ResourceManager.GetString("TimerSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 公告题目 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 今日 的本地化字符串。
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户当日发送短信统计 的本地化字符串。
        /// </summary>
        internal static string TodaySendingRecordofCurrentUser {
            get {
                return ResourceManager.GetString("TodaySendingRecordofCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 当日发送短信统计 的本地化字符串。
        /// </summary>
        internal static string TodaySendingRecordofCurrentUser1 {
            get {
                return ResourceManager.GetString("TodaySendingRecordofCurrentUser1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 @Resources.Language.Twoinputpasswordisnotthesamepleaseinputagain 的本地化字符串。
        /// </summary>
        internal static string Twoinputpasswordisnotthesamepleaseinputagain {
            get {
                return ResourceManager.GetString("Twoinputpasswordisnotthesamepleaseinputagain", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 未登录 的本地化字符串。
        /// </summary>
        internal static string Unlogin {
            get {
                return ResourceManager.GetString("Unlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 未读消息 的本地化字符串。
        /// </summary>
        internal static string UnreadMessage {
            get {
                return ResourceManager.GetString("UnreadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 上级菜单 的本地化字符串。
        /// </summary>
        internal static string UpperMenu {
            get {
                return ResourceManager.GetString("UpperMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发送人 的本地化字符串。
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查询用户 的本地化字符串。
        /// </summary>
        internal static string User1 {
            get {
                return ResourceManager.GetString("User1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户管理 的本地化字符串。
        /// </summary>
        internal static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户名 的本地化字符串。
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户名 的本地化字符串。
        /// </summary>
        internal static string UserName1 {
            get {
                return ResourceManager.GetString("UserName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户权限设置 的本地化字符串。
        /// </summary>
        internal static string UsersRightsSettings {
            get {
                return ResourceManager.GetString("UsersRightsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 分配权限 的本地化字符串。
        /// </summary>
        internal static string UsersRightsSettings1 {
            get {
                return ResourceManager.GetString("UsersRightsSettings1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户角色设置 的本地化字符串。
        /// </summary>
        internal static string UsersRoleSetting {
            get {
                return ResourceManager.GetString("UsersRoleSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 分配角色 的本地化字符串。
        /// </summary>
        internal static string UsersRoleSetting1 {
            get {
                return ResourceManager.GetString("UsersRoleSetting1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 验证码 的本地化字符串。
        /// </summary>
        internal static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否为VIP联系人 的本地化字符串。
        /// </summary>
        internal static string VIP {
            get {
                return ResourceManager.GetString("VIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否VIP 的本地化字符串。
        /// </summary>
        internal static string VIP1 {
            get {
                return ResourceManager.GetString("VIP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否可见 的本地化字符串。
        /// </summary>
        internal static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否由角色赋予 的本地化字符串。
        /// </summary>
        internal static string WhetherGivenByRoles {
            get {
                return ResourceManager.GetString("WhetherGivenByRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 作业名称 的本地化字符串。
        /// </summary>
        internal static string WorkName {
            get {
                return ResourceManager.GetString("WorkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 作业管理 的本地化字符串。
        /// </summary>
        internal static string Works {
            get {
                return ResourceManager.GetString("Works", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 作业调度 的本地化字符串。
        /// </summary>
        internal static string WorksManagement {
            get {
                return ResourceManager.GetString("WorksManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 作业状态 的本地化字符串。
        /// </summary>
        internal static string WorkStatus {
            get {
                return ResourceManager.GetString("WorkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 模板管理 的本地化字符串。
        /// </summary>
        internal static string WorksTemplate {
            get {
                return ResourceManager.GetString("WorksTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 选择指定部门中的全部联系人 的本地化字符串。
        /// </summary>
        internal static string Youcanchangetheselecteddepartment {
            get {
                return ResourceManager.GetString("Youcanchangetheselecteddepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 选择指定群组中的全部联系人 的本地化字符串。
        /// </summary>
        internal static string Youcanchangetheselectedgroup {
            get {
                return ResourceManager.GetString("Youcanchangetheselectedgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设置你常用的
        ///短信任务及常用的群组 的本地化字符串。
        /// </summary>
        internal static string Youcanselectcommonmissionandgroup {
            get {
                return ResourceManager.GetString("Youcanselectcommonmissionandgroup", resourceCulture);
            }
        }
    }
}
