//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSOA.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceTest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceTest() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMSOA.App_GlobalResources.ResourceTest", typeof(ResourceTest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Account 的本地化字符串。
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Contact 的本地化字符串。
        /// </summary>
        public static string AddContact {
            get {
                return ResourceManager.GetString("AddContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced Search 的本地化字符串。
        /// </summary>
        public static string AdvancedSearch {
            get {
                return ResourceManager.GetString("AdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 After… 的本地化字符串。
        /// </summary>
        public static string After {
            get {
                return ResourceManager.GetString("After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Messages 的本地化字符串。
        /// </summary>
        public static string AllMessages {
            get {
                return ResourceManager.GetString("AllMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Users 的本地化字符串。
        /// </summary>
        public static string AllUsers {
            get {
                return ResourceManager.GetString("AllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete it? 的本地化字符串。
        /// </summary>
        public static string Areyousureyouwanttodeleteit {
            get {
                return ResourceManager.GetString("Areyousureyouwanttodeleteit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assign The Right of Work Template 的本地化字符串。
        /// </summary>
        public static string AssignTheRightofWorkTemplate {
            get {
                return ResourceManager.GetString("AssignTheRightofWorkTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authority 的本地化字符串。
        /// </summary>
        public static string Authority {
            get {
                return ResourceManager.GetString("Authority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authority Management 的本地化字符串。
        /// </summary>
        public static string AuthorityManagement {
            get {
                return ResourceManager.GetString("AuthorityManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Before… 的本地化字符串。
        /// </summary>
        public static string Before {
            get {
                return ResourceManager.GetString("Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calendar 的本地化字符串。
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Department 的本地化字符串。
        /// </summary>
        public static string ChangeDepartment {
            get {
                return ResourceManager.GetString("ChangeDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Group 的本地化字符串。
        /// </summary>
        public static string ChangeGroup {
            get {
                return ResourceManager.GetString("ChangeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change a Picture 的本地化字符串。
        /// </summary>
        public static string ChangePicture {
            get {
                return ResourceManager.GetString("ChangePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chart of Recent 10 Messages of Current User 的本地化字符串。
        /// </summary>
        public static string ChartofRecent10MessagesofCurrentUser {
            get {
                return ResourceManager.GetString("ChartofRecent10MessagesofCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chart of Today Sending Record of Current User 的本地化字符串。
        /// </summary>
        public static string ChartofTodaySendingRecordofCurrentUser {
            get {
                return ResourceManager.GetString("ChartofTodaySendingRecordofCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choice 的本地化字符串。
        /// </summary>
        public static string Choice {
            get {
                return ResourceManager.GetString("Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choice a Type 的本地化字符串。
        /// </summary>
        public static string ChoiceaType {
            get {
                return ResourceManager.GetString("ChoiceaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Common Mission and Group Setting 的本地化字符串。
        /// </summary>
        public static string CommonMissionandGroupSetting {
            get {
                return ResourceManager.GetString("CommonMissionandGroupSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contact List 的本地化字符串。
        /// </summary>
        public static string ContactList {
            get {
                return ResourceManager.GetString("ContactList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contact Name 的本地化字符串。
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contacts List 的本地化字符串。
        /// </summary>
        public static string ContactsList {
            get {
                return ResourceManager.GetString("ContactsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contacts List Update Notice 的本地化字符串。
        /// </summary>
        public static string ContactsListUpdateNotice {
            get {
                return ResourceManager.GetString("ContactsListUpdateNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content 的本地化字符串。
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controller Name 的本地化字符串。
        /// </summary>
        public static string ControllerName {
            get {
                return ResourceManager.GetString("ControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Time 的本地化字符串。
        /// </summary>
        public static string CreateTime {
            get {
                return ResourceManager.GetString("CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cron Expressions 的本地化字符串。
        /// </summary>
        public static string CronExpressions {
            get {
                return ResourceManager.GetString("CronExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current User 的本地化字符串。
        /// </summary>
        public static string CurrentUser {
            get {
                return ResourceManager.GetString("CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Contact 的本地化字符串。
        /// </summary>
        public static string DeleteContact {
            get {
                return ResourceManager.GetString("DeleteContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Department List 的本地化字符串。
        /// </summary>
        public static string DepartmentList {
            get {
                return ResourceManager.GetString("DepartmentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Department Management 的本地化字符串。
        /// </summary>
        public static string DepartmentManagement {
            get {
                return ResourceManager.GetString("DepartmentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Department Name 的本地化字符串。
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Department Setting for SMS Mission 的本地化字符串。
        /// </summary>
        public static string DepartmentSettingforSMSMission {
            get {
                return ResourceManager.GetString("DepartmentSettingforSMSMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Describe 的本地化字符串。
        /// </summary>
        public static string Describe {
            get {
                return ResourceManager.GetString("Describe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeskTop 的本地化字符串。
        /// </summary>
        public static string DeskTop {
            get {
                return ResourceManager.GetString("DeskTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable 的本地化字符串。
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 During… 的本地化字符串。
        /// </summary>
        public static string During {
            get {
                return ResourceManager.GetString("During", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Contact 的本地化字符串。
        /// </summary>
        public static string EditContact {
            get {
                return ResourceManager.GetString("EditContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EdiTe 的本地化字符串。
        /// </summary>
        public static string Edite {
            get {
                return ResourceManager.GetString("Edite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable 的本地化字符串。
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable/Disable 的本地化字符串。
        /// </summary>
        public static string EnableDisable {
            get {
                return ResourceManager.GetString("EnableDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End Time 的本地化字符串。
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter the phone number 的本地化字符串。
        /// </summary>
        public static string Enterthephonenumber {
            get {
                return ResourceManager.GetString("Enterthephonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter the same password 的本地化字符串。
        /// </summary>
        public static string Enterthesamepassword {
            get {
                return ResourceManager.GetString("Enterthesamepassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execution Time 的本地化字符串。
        /// </summary>
        public static string ExecutionTime {
            get {
                return ResourceManager.GetString("ExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go 的本地化字符串。
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group 的本地化字符串。
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group List 的本地化字符串。
        /// </summary>
        public static string GroupList {
            get {
                return ResourceManager.GetString("GroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group Management 的本地化字符串。
        /// </summary>
        public static string GroupManagement {
            get {
                return ResourceManager.GetString("GroupManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group Name 的本地化字符串。
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group Setting for SMS Mission 的本地化字符串。
        /// </summary>
        public static string GroupSettingforSMSMission {
            get {
                return ResourceManager.GetString("GroupSettingforSMSMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter your account and password
        ///If you have any problems  please Contact the administraTor. 的本地化字符串。
        /// </summary>
        public static string Hint {
            get {
                return ResourceManager.GetString("Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input SMS content please… 的本地化字符串。
        /// </summary>
        public static string InputSMScontentplease {
            get {
                return ResourceManager.GetString("InputSMScontentplease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input template content… 的本地化字符串。
        /// </summary>
        public static string Inputtemplatecontent {
            get {
                return ResourceManager.GetString("Inputtemplatecontent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job Class Name 的本地化字符串。
        /// </summary>
        public static string JobClassName {
            get {
                return ResourceManager.GetString("JobClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Week 的本地化字符串。
        /// </summary>
        public static string LastWeek {
            get {
                return ResourceManager.GetString("LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logout 的本地化字符串。
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message List 的本地化字符串。
        /// </summary>
        public static string MessageList {
            get {
                return ResourceManager.GetString("MessageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Messages 的本地化字符串。
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Messages Management 的本地化字符串。
        /// </summary>
        public static string MessagesManagement {
            get {
                return ResourceManager.GetString("MessagesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message Type 的本地化字符串。
        /// </summary>
        public static string MessageType {
            get {
                return ResourceManager.GetString("MessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method Name 的本地化字符串。
        /// </summary>
        public static string MethodName {
            get {
                return ResourceManager.GetString("MethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mission 的本地化字符串。
        /// </summary>
        public static string Mission {
            get {
                return ResourceManager.GetString("Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mission List 的本地化字符串。
        /// </summary>
        public static string MissionList {
            get {
                return ResourceManager.GetString("MissionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mission Management 的本地化字符串。
        /// </summary>
        public static string MissionManagement {
            get {
                return ResourceManager.GetString("MissionManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mission Name 的本地化字符串。
        /// </summary>
        public static string MissionName {
            get {
                return ResourceManager.GetString("MissionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modified Time 的本地化字符串。
        /// </summary>
        public static string ModifiedTime {
            get {
                return ResourceManager.GetString("ModifiedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify Password 的本地化字符串。
        /// </summary>
        public static string ModifyPassword {
            get {
                return ResourceManager.GetString("ModifyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Into Group 的本地化字符串。
        /// </summary>
        public static string MoveIntoGroup {
            get {
                return ResourceManager.GetString("MoveIntoGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name Maching 的本地化字符串。
        /// </summary>
        public static string NameMaching {
            get {
                return ResourceManager.GetString("NameMaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Message 的本地化字符串。
        /// </summary>
        public static string NewMessage {
            get {
                return ResourceManager.GetString("NewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Password 的本地化字符串。
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Execution Time 的本地化字符串。
        /// </summary>
        public static string NextExecutionTime {
            get {
                return ResourceManager.GetString("NextExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Received 的本地化字符串。
        /// </summary>
        public static string NotReceived {
            get {
                return ResourceManager.GetString("NotReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number Matching 的本地化字符串。
        /// </summary>
        public static string NumberMatching {
            get {
                return ResourceManager.GetString("NumberMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation 的本地化字符串。
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation List 的本地化字符串。
        /// </summary>
        public static string OperationList {
            get {
                return ResourceManager.GetString("OperationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optional 的本地化字符串。
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optional  Cron expression 的本地化字符串。
        /// </summary>
        public static string OptionalCronexpression {
            get {
                return ResourceManager.GetString("OptionalCronexpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order 的本地化字符串。
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other Notice 的本地化字符串。
        /// </summary>
        public static string OtherNotice {
            get {
                return ResourceManager.GetString("OtherNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phone number 的本地化字符串。
        /// </summary>
        public static string Phonenumber {
            get {
                return ResourceManager.GetString("Phonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please choose the superior of this department. 的本地化字符串。
        /// </summary>
        public static string Pleasechoosethesuperiorofthisdepartment {
            get {
                return ResourceManager.GetString("Pleasechoosethesuperiorofthisdepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please describe the group (optional) 的本地化字符串。
        /// </summary>
        public static string Pleasedescribethegroupoptional {
            get {
                return ResourceManager.GetString("Pleasedescribethegroupoptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a new login password 的本地化字符串。
        /// </summary>
        public static string Pleaseenteranewloginpassword {
            get {
                return ResourceManager.GetString("Pleaseenteranewloginpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a subject. 的本地化字符串。
        /// </summary>
        public static string Pleaseenterasubject {
            get {
                return ResourceManager.GetString("Pleaseenterasubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter password. 的本地化字符串。
        /// </summary>
        public static string Pleaseenterpassword {
            get {
                return ResourceManager.GetString("Pleaseenterpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter password again 的本地化字符串。
        /// </summary>
        public static string Pleaseenterpasswordagain {
            get {
                return ResourceManager.GetString("Pleaseenterpasswordagain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the class name. 的本地化字符串。
        /// </summary>
        public static string Pleaseentertheclassname {
            get {
                return ResourceManager.GetString("Pleaseentertheclassname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the contact name 的本地化字符串。
        /// </summary>
        public static string Pleaseenterthecontactname {
            get {
                return ResourceManager.GetString("Pleaseenterthecontactname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the content of this template. 的本地化字符串。
        /// </summary>
        public static string Pleaseenterthecontentofthistemplate {
            get {
                return ResourceManager.GetString("Pleaseenterthecontentofthistemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the controller name 的本地化字符串。
        /// </summary>
        public static string Pleaseenterthecontrollername {
            get {
                return ResourceManager.GetString("Pleaseenterthecontrollername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the CronStr. 的本地化字符串。
        /// </summary>
        public static string PleaseentertheCronStr {
            get {
                return ResourceManager.GetString("PleaseentertheCronStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the group name 的本地化字符串。
        /// </summary>
        public static string Pleaseenterthegroupname {
            get {
                return ResourceManager.GetString("Pleaseenterthegroupname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the group of this work. 的本地化字符串。
        /// </summary>
        public static string Pleaseenterthegroupofthiswork {
            get {
                return ResourceManager.GetString("Pleaseenterthegroupofthiswork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the name of right. 的本地化字符串。
        /// </summary>
        public static string Pleaseenterthenameofright {
            get {
                return ResourceManager.GetString("Pleaseenterthenameofright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the name of the area 的本地化字符串。
        /// </summary>
        public static string Pleaseenterthenameofthearea {
            get {
                return ResourceManager.GetString("Pleaseenterthenameofthearea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the name of the controller 的本地化字符串。
        /// </summary>
        public static string Pleaseenterthenameofthecontroller {
            get {
                return ResourceManager.GetString("Pleaseenterthenameofthecontroller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the name of the department. 的本地化字符串。
        /// </summary>
        public static string Pleaseenterthenameofthedepartment {
            get {
                return ResourceManager.GetString("Pleaseenterthenameofthedepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the name of the mission. 的本地化字符串。
        /// </summary>
        public static string Pleaseenterthenameofthemission {
            get {
                return ResourceManager.GetString("Pleaseenterthenameofthemission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the role name. 的本地化字符串。
        /// </summary>
        public static string Pleaseentertherolename {
            get {
                return ResourceManager.GetString("Pleaseentertherolename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the template Name 的本地化字符串。
        /// </summary>
        public static string PleaseenterthetemplateName {
            get {
                return ResourceManager.GetString("PleaseenterthetemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the template type (integer) 的本地化字符串。
        /// </summary>
        public static string Pleaseenterthetemplatetypeinteger {
            get {
                return ResourceManager.GetString("Pleaseenterthetemplatetypeinteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the title no more than 50 words 的本地化字符串。
        /// </summary>
        public static string Pleaseenterthetitlenomorethan50words {
            get {
                return ResourceManager.GetString("Pleaseenterthetitlenomorethan50words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the work template&apos;s class name. 的本地化字符串。
        /// </summary>
        public static string Pleaseentertheworktemplatesclassname {
            get {
                return ResourceManager.GetString("Pleaseentertheworktemplatesclassname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the work template&apos;s group name. 的本地化字符串。
        /// </summary>
        public static string Pleaseentertheworktemplatesgroupname {
            get {
                return ResourceManager.GetString("Pleaseentertheworktemplatesgroupname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter user name. 的本地化字符串。
        /// </summary>
        public static string Pleaseenterusername {
            get {
                return ResourceManager.GetString("Pleaseenterusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter work name. 的本地化字符串。
        /// </summary>
        public static string Pleaseenterworkname {
            get {
                return ResourceManager.GetString("Pleaseenterworkname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please fill in the template Name 的本地化字符串。
        /// </summary>
        public static string PleasefillinthetemplateName {
            get {
                return ResourceManager.GetString("PleasefillinthetemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Select 的本地化字符串。
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a person 的本地化字符串。
        /// </summary>
        public static string Pleaseselectaperson {
            get {
                return ResourceManager.GetString("Pleaseselectaperson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select the suitable mission for this template. 的本地化字符串。
        /// </summary>
        public static string Pleaseselectthesuitablemissionforthistemplate {
            get {
                return ResourceManager.GetString("Pleaseselectthesuitablemissionforthistemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select your common groups.
        ///Selected groups will appears in the list of message sending interface. 的本地化字符串。
        /// </summary>
        public static string Pleaseselectyourcommongroups {
            get {
                return ResourceManager.GetString("Pleaseselectyourcommongroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Priority 的本地化字符串。
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SMS Platform of NMEFC 的本地化字符串。
        /// </summary>
        public static string ProjectFullName {
            get {
                return ResourceManager.GetString("ProjectFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SMS Platform of NMEFC 的本地化字符串。
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prompt 的本地化字符串。
        /// </summary>
        public static string Prompt {
            get {
                return ResourceManager.GetString("Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query 的本地化字符串。
        /// </summary>
        public static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query  AuthorizationName 的本地化字符串。
        /// </summary>
        public static string QueryAuthorizationName {
            get {
                return ResourceManager.GetString("QueryAuthorizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query Controller Name 的本地化字符串。
        /// </summary>
        public static string QueryControllerName {
            get {
                return ResourceManager.GetString("QueryControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query Method Name 的本地化字符串。
        /// </summary>
        public static string QueryMethodName {
            get {
                return ResourceManager.GetString("QueryMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query Region Name 的本地化字符串。
        /// </summary>
        public static string QueryRegionName {
            get {
                return ResourceManager.GetString("QueryRegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query Remarks 的本地化字符串。
        /// </summary>
        public static string QueryRemarks {
            get {
                return ResourceManager.GetString("QueryRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query Role Name 的本地化字符串。
        /// </summary>
        public static string QueryRoleName {
            get {
                return ResourceManager.GetString("QueryRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query User Name 的本地化字符串。
        /// </summary>
        public static string QueryUserName {
            get {
                return ResourceManager.GetString("QueryUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role&apos;s Authorization Settings 的本地化字符串。
        /// </summary>
        public static string RAuthorizationSettings {
            get {
                return ResourceManager.GetString("RAuthorizationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Received 的本地化字符串。
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Receiving 的本地化字符串。
        /// </summary>
        public static string Receiving {
            get {
                return ResourceManager.GetString("Receiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recent 10 Messages of Current User 的本地化字符串。
        /// </summary>
        public static string Recent10MessagesofCurrentUser {
            get {
                return ResourceManager.GetString("Recent10MessagesofCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recovery 的本地化字符串。
        /// </summary>
        public static string Recovery {
            get {
                return ResourceManager.GetString("Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recycle 的本地化字符串。
        /// </summary>
        public static string Recycle {
            get {
                return ResourceManager.GetString("Recycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 region 的本地化字符串。
        /// </summary>
        public static string region {
            get {
                return ResourceManager.GetString("region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Region Name 的本地化字符串。
        /// </summary>
        public static string RegionName {
            get {
                return ResourceManager.GetString("RegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Release Time 的本地化字符串。
        /// </summary>
        public static string ReleaseTime {
            get {
                return ResourceManager.GetString("ReleaseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remarks 的本地化字符串。
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remember Me 的本地化字符串。
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Request Type 的本地化字符串。
        /// </summary>
        public static string RequestType {
            get {
                return ResourceManager.GetString("RequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset Password 的本地化字符串。
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right Name 的本地化字符串。
        /// </summary>
        public static string RightName {
            get {
                return ResourceManager.GetString("RightName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role Management 的本地化字符串。
        /// </summary>
        public static string RoleManagement {
            get {
                return ResourceManager.GetString("RoleManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role Name 的本地化字符串。
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User&apos;s Role Setting 的本地化字符串。
        /// </summary>
        public static string RoleSetting {
            get {
                return ResourceManager.GetString("RoleSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a mission 的本地化字符串。
        /// </summary>
        public static string Selectamission {
            get {
                return ResourceManager.GetString("Selectamission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select your common missions.
        ///Selected missions will appears in the list of message sending interface. 的本地化字符串。
        /// </summary>
        public static string SelectCommonMission {
            get {
                return ResourceManager.GetString("SelectCommonMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Date 的本地化字符串。
        /// </summary>
        public static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Department 的本地化字符串。
        /// </summary>
        public static string SelectDepartment {
            get {
                return ResourceManager.GetString("SelectDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select one line of data at least. 的本地化字符串。
        /// </summary>
        public static string Selectonelineofdataatleast {
            get {
                return ResourceManager.GetString("Selectonelineofdataatleast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the area of the Department 的本地化字符串。
        /// </summary>
        public static string SelecttheareaoftheDepartment {
            get {
                return ResourceManager.GetString("SelecttheareaoftheDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the department 的本地化字符串。
        /// </summary>
        public static string Selectthedepartment {
            get {
                return ResourceManager.GetString("Selectthedepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the type of message 的本地化字符串。
        /// </summary>
        public static string Selectthetypeofmessage {
            get {
                return ResourceManager.GetString("Selectthetypeofmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the upper menu for this permission 的本地化字符串。
        /// </summary>
        public static string Selecttheuppermenuforthispermission {
            get {
                return ResourceManager.GetString("Selecttheuppermenuforthispermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send 的本地化字符串。
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send Number 的本地化字符串。
        /// </summary>
        public static string SendNumber {
            get {
                return ResourceManager.GetString("SendNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send SMS 的本地化字符串。
        /// </summary>
        public static string SendSMS {
            get {
                return ResourceManager.GetString("SendSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send Statistics 的本地化字符串。
        /// </summary>
        public static string SendStatistics {
            get {
                return ResourceManager.GetString("SendStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send Time 的本地化字符串。
        /// </summary>
        public static string SendTime {
            get {
                return ResourceManager.GetString("SendTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Common Group 的本地化字符串。
        /// </summary>
        public static string SetCommonGroup {
            get {
                return ResourceManager.GetString("SetCommonGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SetCommonMission 的本地化字符串。
        /// </summary>
        public static string SetCommonMission {
            get {
                return ResourceManager.GetString("SetCommonMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set VIP contacts 的本地化字符串。
        /// </summary>
        public static string SetVIPcontacts {
            get {
                return ResourceManager.GetString("SetVIPcontacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show XX to XX in XX records 的本地化字符串。
        /// </summary>
        public static string Showrecords {
            get {
                return ResourceManager.GetString("Showrecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign In 的本地化字符串。
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single Day 的本地化字符串。
        /// </summary>
        public static string SingleDay {
            get {
                return ResourceManager.GetString("SingleDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SMS 的本地化字符串。
        /// </summary>
        public static string SMS {
            get {
                return ResourceManager.GetString("SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SMS Content 的本地化字符串。
        /// </summary>
        public static string SMSContent {
            get {
                return ResourceManager.GetString("SMSContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SMS Editor 的本地化字符串。
        /// </summary>
        public static string SMSEditor {
            get {
                return ResourceManager.GetString("SMSEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SMS Mission 的本地化字符串。
        /// </summary>
        public static string SMSMission {
            get {
                return ResourceManager.GetString("SMSMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SMS Task Name 的本地化字符串。
        /// </summary>
        public static string SMSTaskName {
            get {
                return ResourceManager.GetString("SMSTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Statistics 的本地化字符串。
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (第几页)/（共几页） 的本地化字符串。
        /// </summary>
        public static string String53 {
            get {
                return ResourceManager.GetString("String53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subject 的本地化字符串。
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suitable Mission 的本地化字符串。
        /// </summary>
        public static string SuitableMission {
            get {
                return ResourceManager.GetString("SuitableMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Superior Department 的本地化字符串。
        /// </summary>
        public static string SuperiorDepartment {
            get {
                return ResourceManager.GetString("SuperiorDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suspend 的本地化字符串。
        /// </summary>
        public static string Suspend {
            get {
                return ResourceManager.GetString("Suspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Maintenance Notice 的本地化字符串。
        /// </summary>
        public static string SystemMaintenanceNotice {
            get {
                return ResourceManager.GetString("SystemMaintenanceNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Template 的本地化字符串。
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Template class 的本地化字符串。
        /// </summary>
        public static string Templateclass {
            get {
                return ResourceManager.GetString("Templateclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Template Group Name 的本地化字符串。
        /// </summary>
        public static string TemplateGroupName {
            get {
                return ResourceManager.GetString("TemplateGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Template Name 的本地化字符串。
        /// </summary>
        public static string TemplateName {
            get {
                return ResourceManager.GetString("TemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Temporary Contacts 的本地化字符串。
        /// </summary>
        public static string TemporaryContacts {
            get {
                return ResourceManager.GetString("TemporaryContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Termination 的本地化字符串。
        /// </summary>
        public static string Termination {
            get {
                return ResourceManager.GetString("Termination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The message sending time. 的本地化字符串。
        /// </summary>
        public static string Themessagesendingtime {
            get {
                return ResourceManager.GetString("Themessagesendingtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The smaller the number the higher the priority. 的本地化字符串。
        /// </summary>
        public static string Thesmallerthenumberthehigherthepriority {
            get {
                return ResourceManager.GetString("Thesmallerthenumberthehigherthepriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The switch of delayed sending 的本地化字符串。
        /// </summary>
        public static string Theswitchofdelayedsending {
            get {
                return ResourceManager.GetString("Theswitchofdelayedsending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The time of work execution 的本地化字符串。
        /// </summary>
        public static string Thetimeofworkexecution {
            get {
                return ResourceManager.GetString("Thetimeofworkexecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This Month 的本地化字符串。
        /// </summary>
        public static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timer On/Off 的本地化字符串。
        /// </summary>
        public static string TimerOnOff {
            get {
                return ResourceManager.GetString("TimerOnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timer Setting 的本地化字符串。
        /// </summary>
        public static string TimerSetting {
            get {
                return ResourceManager.GetString("TimerSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Today 的本地化字符串。
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Today Sending Record of Current User 的本地化字符串。
        /// </summary>
        public static string TodaySendingRecordofCurrentUser {
            get {
                return ResourceManager.GetString("TodaySendingRecordofCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User&apos;s Authorization Settings 的本地化字符串。
        /// </summary>
        public static string UAuthorizationSettings {
            get {
                return ResourceManager.GetString("UAuthorizationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unread Message 的本地化字符串。
        /// </summary>
        public static string UnreadMessage {
            get {
                return ResourceManager.GetString("UnreadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upper Menu 的本地化字符串。
        /// </summary>
        public static string UpperMenu {
            get {
                return ResourceManager.GetString("UpperMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User&apos;s Role Setting 的本地化字符串。
        /// </summary>
        public static string URoleSetting {
            get {
                return ResourceManager.GetString("URoleSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User 的本地化字符串。
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Management 的本地化字符串。
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Name 的本地化字符串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verification Code 的本地化字符串。
        /// </summary>
        public static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VIP 的本地化字符串。
        /// </summary>
        public static string VIP {
            get {
                return ResourceManager.GetString("VIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visible 的本地化字符串。
        /// </summary>
        public static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Work Name 的本地化字符串。
        /// </summary>
        public static string WorkName {
            get {
                return ResourceManager.GetString("WorkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Works 的本地化字符串。
        /// </summary>
        public static string Works {
            get {
                return ResourceManager.GetString("Works", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Works Management 的本地化字符串。
        /// </summary>
        public static string WorksManagement {
            get {
                return ResourceManager.GetString("WorksManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Work Status 的本地化字符串。
        /// </summary>
        public static string WorkStatus {
            get {
                return ResourceManager.GetString("WorkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Works Template 的本地化字符串。
        /// </summary>
        public static string WorksTemplate {
            get {
                return ResourceManager.GetString("WorksTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can change the selected department. 的本地化字符串。
        /// </summary>
        public static string Youcanchangetheselecteddepartment {
            get {
                return ResourceManager.GetString("Youcanchangetheselecteddepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can change the selected group. 的本地化字符串。
        /// </summary>
        public static string Youcanchangetheselectedgroup {
            get {
                return ResourceManager.GetString("Youcanchangetheselectedgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can select common mission and group. 的本地化字符串。
        /// </summary>
        public static string Youcanselectcommonmissionandgroup {
            get {
                return ResourceManager.GetString("Youcanselectcommonmissionandgroup", resourceCulture);
            }
        }
    }
}
